[package]
name = "stage_config"
version = "1.1.1"
authors = ["ThatNintendoNerd"]
edition = "2024"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
arcropolis-api = { git = "https://github.com/Raytwo/arcropolis_api.git" }
libc2 = { git = "https://github.com/ultimate-research/libc2-rs.git", features = ["impl", "serde"] }
memchr = "2.8.3"
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
skyline = "0.6.0"
toml = "1.1.6"
walkdir = "2.5.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
